### ISSUE TITLE
好多文件都是无效文件

### ISSUE THREAD

**Issue by xiaohui-yan** [i0Ek3/BLANK#1]

**Comment by i0Ek3** [comment]
可以具体描述一下吗？我之前遇到了133KB这个问题，不知道是不是这个？

**Comment by i0Ek3** [comment]
@xiaohui-yan 可以具体描述一下吗？我之前遇到了133KB这个问题，不知道是不是这个？

**Comment by i0Ek3** [comment]
可以具体描述一下吗？我之前遇到了133B这个问题，不知道是不是这个？

**Comment by i0Ek3** [comment]
@xiaohui-yan 可以具体描述一下吗？我之前遇到了133B这个问题，不知道是不是这个？

**Comment by xiaohui-yan** [comment]
您好，
     在github https://github.com/i0Ek3/BLANK/tree/master/tech-books 路径下有好多书籍都是无效的，不可预览。下载后是空的pdf文件。
在github上点击单个下载的时候报Sorry, this file is invalid so it cannot be displayed.
    附截图两个



------------------ 原始邮件 ------------------
发件人: "i0Ek3"<notifications@github.com>;
发送时间: 2019年7月21日(星期天) 下午4:52
收件人: "i0Ek3/BLANK"<BLANK@noreply.github.com>;
抄送: "经历决定眼界"<1076242600@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [i0Ek3/BLANK] 好多文件都是无效文件 (#1)




可以具体描述一下吗？我之前遇到了133KB这个问题，不知道是不是这个？

**Comment by i0Ek3** [comment]
@xiaohui-yan 我大概知道是什么问题了，今晚我试着解决一下，感谢你的反馈～

**Comment by i0Ek3** [comment]
@xiaohui-yan GitHub 这边暂且无法上传书籍了，你可以到https://git.angry.im/i0Ek3/blank/src/branch/master/tech-books 这里下载，我上传了大部分书籍。阅读愉快～

**Comment by xiaohui-yan** [comment]
非常感谢，谢谢您了
  

 

 ------------------ 原始邮件 ------------------
  发件人: "i0Ek3"<notifications@github.com>;
 发送时间: 2019年7月23日(星期二) 下午3:41
 收件人: "i0Ek3/BLANK"<BLANK@noreply.github.com>;
 抄送: "经历决定眼界"<1076242600@qq.com>;"Mention"<mention@noreply.github.com>;
 主题: Re: [i0Ek3/BLANK] 好多文件都是无效文件 (#1)

 

 
@xiaohui-yan GitHub 这边暂且无法上传书籍了，你可以到https://git.angry.im/i0Ek3/blank/src/branch/master/tech-books 这里下载，我上传了大部分书籍。阅读愉快～

**Comment by i0Ek3** [comment]
日后还有其他问题，欢迎提issue告知，我先关了哈！
